spring:
  application.name: finess
  config.import: classpath:secret.yaml

  liquibase:
    change-log: classpath:db/changelog/changelog-root.yaml

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

finess:
  payment:
    initialization:
      fixedDelay: PT15S
      batchSize: 10
      retryLimit: 3
      executor:
        corePoolSize: 3
        maxPoolSize: 5
        queueCapacity: 100
    status.actualizer:
      fixedDelay: PT15S
      batchSize: 10