spring:
  application.name: finess
  config.import: classpath:secret.yaml

  liquibase:
    change-log: classpath:db/changelog/changelog-root.yaml

  jpa:
    open-in-view: false

finess:
  payment:
    initialization:
      fixedDelay: PT1M
      batchSize: 10
      retryLimit: 3
      executor:
        corePoolSize: 3
        maxPoolSize: 5
        queueCapacity: 100

v2:
  url: https://rest-api-test.tinkoff.ru